- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present
    update_cache: yes
- name: Copy dnsmasq configuration file
  copy:
    src: "{{ inventory_hostname }}/dnsmasq.conf"
    dest: /etc/dnsmasq.conf
  notify: Restart dnsmasq
