routers:
  hosts:
    router:
      static_interfaces:
      - name: "eth1"
        ip: "10.100.0.1"
        netmask: "255.255.0.0"
      - name: "eth2"
        ip: "10.200.0.1"
        netmask: "255.255.0.0"
      dnsmasq:
        interfaces:
        - "eth1"
        - "eth2"
        ranges:
        - begin: "10.100.1.1"
          end: "10.100.9.254"
          lease: "12h"
        - begin: "10.200.1.1"
          end: "10.200.9.254"
          lease: "12h"
        ntp_servers:
        - "10.100.0.1"
        - "10.200.0.1"
        dns_servers:
        - "10.100.0.1"
        - "10.200.0.1"
        routes:
        - network1: "10.200.0.0/16"
          gateway1: "10.100.0.1"
          network2: "10.100.0.0/16"
          gateway2: "10.200.0.1"
        fixed_hosts:
        - mac: "08:00:27:09:A5:01"
          ip: "10.200.2.1"
          hostname: "servermain"
          lease: "12h"
    router2:
      static_interfaces:
      - name: "eth1"
        ip: "10.200.0.254"
        netmask: "255.255.0.0"
      - name: "eth2"
        ip: "10.30.0.1"
        netmask: "255.255.0.0"
      routes:
      - name: "eth1"
        dest: "10.100.0.0/16"
        gateway: "10.200.0.1"
      dnsmasq:
        interfaces:
        - "eth1"
        - "eth2"
        ranges:
        - begin: "10.30.1.1"
          end: "10.30.1.254"
          lease: "12h"
        ntp_servers:
        - "10.30.0.1"
        dns_servers:
        - "10.30.0.1"
        routes:
        - network: "10.100.0.0/16"
          gateway: "10.30.0.1"
        fixed_hosts:
        - mac: "08:00:27:09:A5:01"
          ip: "10.30.2.1"
          hostname: "servermain"
          lease: "12h"
