routers:
  hosts:
    router:
      static_interfaces:
      - name: "eth1"
        ip: "10.100.0.1"
        netmask: "255.255.0.0"
      - name: "eth2"
        ip: "10.200.0.1"
        netmask: "255.255.0.0"
      dnsmasq:
        interfaces:
        - "eth1"
        - "eth2"
        ranges:
        - begin: "10.100.1.1"
          end: "10.100.9.254"
          lease: "12h"
        - begin: "10.200.1.1"
          end: "10.200.2.254"
          lease: "12h"
        # ntp_servers:
        # - "10.10.10.254"
        # - "20.20.0.1"
        dns_servers:
        - "10.100.1.1"
        routes:
        - name: "eth1"
          network: "10.200.0.0/16"
          gateway: "10.100.0.1"
        - name: "eth2"
          network: "10.100.0.0/16"
          gateway: "10.200.0.1"
        fixed_hosts:
        - mac: "08:00:27:09:A5:01"
          ip: "10.200.2.1"
          hostname: "servermain"
          lease: "12h"
    router2:
      static_interfaces:
      - name: "eth1"
        ip: "10.222.222.1"
        netmask: "255.255.255.0"
      - name: "eth2"
        ip: "192.168.56.222"
        netmask: "255.255.255.0"
      routes:
      - name: "eth2"
        dest: "10.111.111.0/24"
        gateway: "192.168.56.111"
      dnsmasq:
        interfaces:
        - "eth1"
        ranges:
        - begin: "10.222.222.100"
          end: "10.222.222.200"
          lease: "12h"
            #ntp_servers:
            #- "10.30.0.1"
        dns_servers:
        - "10.222.222.1"
        routes:
        - name: "eth1"
          network: "10.111.111.0/24"
          gateway: "10.222.222.1"
            # fixed_hosts:
            #- mac: "08:00:27:09:A5:01"
            #ip: "10.30.2.1"
            #hostname: "servermain"
            #lease: "12h"
